'use client'

import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import ReactMarkdown from 'react-markdown'
import { motion, useScroll, useSpring, useTransform } from 'framer-motion'
import { ArrowUpRight, Code, Mail, ExternalLink, MapPin, Menu, X } from 'lucide-react'
import { projects, techStack, type Project } from '@/data/projects'
import { experience } from '@/data/experience'
import { skillGroups } from '@/data/skills'

const ease = [0.22, 1, 0.36, 1] as const
const reveal = { hidden: { opacity: 0, y: 36 }, visible: { opacity: 1, y: 0, transition: { duration: 0.38, ease } } }
const stagger = { hidden: {}, visible: { transition: { staggerChildren: 0.08 } } }

type BrandIconProps = { size?: number; className?: string }

function GitHubIcon({ size = 18, className }: BrandIconProps) {
  return <svg viewBox="0 0 24 24" width={size} height={size} fill="currentColor" aria-hidden="true" className={className}><path d="M12 2A10 10 0 0 0 9 21.55c.5.08.68-.22.68-.48v-1.7c-2.78.6-3.37-1.2-3.37-1.2-.46-1.16-1.1-1.46-1.1-1.46-.9-.62.07-.61.07-.61 1 .07 1.53 1.03 1.53 1.03.89 1.52 2.33 1.08 2.9.83.09-.65.35-1.08.64-1.33-2.22-.25-4.56-1.12-4.56-4.97 0-1.1.39-2 1.03-2.7-.1-.25-.45-1.27.1-2.64 0 0 .85-.28 2.78 1.03a9.7 9.7 0 0 1 5.06 0c1.93-1.31 2.78-1.03 2.78-1.03.55 1.37.2 2.39.1 2.64.64.7 1.03 1.6 1.03 2.7 0 3.86-2.34 4.71-4.57 4.96.36.32.68.94.68 1.9v2.82c0 .26.18.57.68.48A10 10 0 0 0 12 2z" /></svg>
}

function LinkedInIcon({ size = 18, className }: BrandIconProps) {
  return <svg viewBox="0 0 24 24" width={size} height={size} fill="currentColor" aria-hidden="true" className={className}><path d="M4.98 3.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM3 9h4v12H3zM9 9h3.83v1.64h.06c.53-1 1.84-2.06 3.8-2.06C20.62 8.58 21 11 21 14.1V21h-4v-6.1c0-1.46-.03-3.33-2.03-3.33-2.04 0-2.35 1.59-2.35 3.23V21H9z" /></svg>
}

function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="mono mb-5 text-xs uppercase tracking-[0.22em] text-amber">{children}</p> }

function sendContactEmail(event: FormEvent<HTMLFormElement>) {
  event.preventDefault()
  const form = new FormData(event.currentTarget)
  const name = String(form.get('name') || '').trim()
  const email = String(form.get('email') || '').trim()
  const message = String(form.get('message') || '').trim()
  const subject = encodeURIComponent(`Portfolio enquiry from ${name || 'a visitor'}`)
  const body = encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\n${message}`)
  window.location.href = `mailto:ashish19@somaiya.edu?subject=${subject}&body=${body}`
}

export function ScrollProgress() { const { scrollYProgress } = useScroll(); const scaleX = useSpring(scrollYProgress, { stiffness: 120, damping: 28, mass: 0.2 }); return <motion.div aria-hidden="true" style={{ scaleX, transformOrigin: '0%' }} className="fixed inset-x-0 top-0 z-[60] h-0.5 bg-amber" /> }

export function Navbar() { const [open, setOpen] = useState(false); const [visible, setVisible] = useState(true); const [last, setLast] = useState(0)
  useEffect(() => { const on = () => { const y = window.scrollY; setVisible(y < 80 || y < last); setLast(y) }; window.addEventListener('scroll', on, { passive: true }); return () => window.removeEventListener('scroll', on) }, [last])
  return <header className={`fixed inset-x-0 top-0 z-50 transition-transform duration-300 ${visible ? 'translate-y-0' : '-translate-y-full'}`}><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-10"><a href="#top" className="flex items-center gap-3 font-display text-xl font-bold tracking-tight"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-amber/50 bg-amber/10 text-sm text-amber">AK</span><span className="sr-only">Ashish Kumar</span></a><button aria-label="Toggle menu" className="md:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><div className={`${open ? 'flex' : 'hidden'} absolute left-5 right-5 top-16 flex-col gap-4 border border-line bg-panel p-5 md:static md:flex md:flex-row md:border-0 md:bg-transparent md:p-0`}>{['Projects','Experience','Skills','About','Contact'].map(x => <a key={x} href={`#${x.toLowerCase()}`} onClick={() => setOpen(false)} className="mono text-xs uppercase tracking-widest text-muted transition-colors hover:text-amber">{x}</a>)}<Link href="/blog" onClick={() => setOpen(false)} className="mono text-xs uppercase tracking-widest text-muted transition-colors hover:text-amber">Blog</Link></div></nav></header> }

function ProfilePhoto() { const [hasPhoto, setHasPhoto] = useState(true); return <motion.div initial={{ opacity: 0, scale: 0.86 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.45, delay: 0.12, ease }} className="flex h-32 w-32 shrink-0 items-center justify-center overflow-hidden rounded-full border border-line bg-panel text-amber md:h-40 md:w-40">{hasPhoto ? <Image src="/ashish-kumar-profile.jpg" alt="Ashish Kumar" width={640} height={800} priority className="h-full w-full object-cover object-[center_18%]" onError={() => setHasPhoto(false)} /> : <span className="font-display text-4xl font-bold tracking-[-0.08em]">AK</span>}</motion.div> }

export function Hero() { const { scrollY } = useScroll(); const gridY = useTransform(scrollY, [0, 700], [0, 110]); return <section id="top" className="relative mx-auto flex min-h-[86vh] max-w-7xl items-center overflow-hidden px-5 pb-14 pt-32 md:px-10"><motion.div aria-hidden="true" style={{ y: gridY }} className="pointer-events-none absolute inset-x-0 -top-24 bottom-0 opacity-30 [background-image:linear-gradient(rgba(245,166,35,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(245,166,35,.08)_1px,transparent_1px)] [background-size:72px_72px]" /><motion.div initial="hidden" animate="visible" variants={reveal} className="relative w-full max-w-5xl"><div className="flex items-center gap-6 md:gap-10"><ProfilePhoto /><div className="flex min-w-0 flex-1 flex-col justify-center"><h1 className="font-display text-4xl font-bold leading-none tracking-[-0.07em] md:text-6xl">Ashish <span className="text-amber">Kumar</span></h1><p className="mono mt-3 text-sm text-muted">Software Engineer</p><p className="mt-4 max-w-2xl text-sm leading-relaxed text-soft md:text-base">I&apos;m a final-year <span className="rounded-sm bg-amber/15 px-1.5 py-0.5 text-amber">Computer Engineering</span> student at <span className="rounded-sm bg-amber/15 px-1.5 py-0.5 text-amber">K. J. Somaiya College of Engineering</span>, Mumbai, passionate about building impactful software and exploring new technologies.</p></div></div><div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="magnetic inline-flex items-center gap-2 bg-amber px-5 py-3 text-sm font-semibold text-ink">View Projects <ArrowUpRight size={16} /></a><a href="/Ashish_Kumar_cv.pdf" target="_blank" rel="noreferrer" className="magnetic inline-flex items-center gap-2 border border-line px-5 py-3 text-sm font-semibold text-soft hover:border-amber hover:text-amber">View / Download Resume <ArrowUpRight size={16} /></a></div><div className="mt-12 flex flex-wrap gap-3 text-muted"><a aria-label="GitHub" href="https://github.com/sentiashish" className="inline-flex items-center gap-2 border border-line bg-panel px-3 py-2 text-xs uppercase tracking-[0.12em] transition-colors hover:border-amber hover:text-amber"><GitHubIcon size={16} /><span>GitHub</span></a><a aria-label="LinkedIn" href="https://linkedin.com/in/ashish-kumar-sentiashish" className="inline-flex items-center gap-2 border border-line bg-panel px-3 py-2 text-xs uppercase tracking-[0.12em] transition-colors hover:border-amber hover:text-amber"><LinkedInIcon size={16} /><span>LinkedIn</span></a><a aria-label="Email" href="mailto:ashish19@somaiya.edu" className="inline-flex items-center gap-2 border border-line bg-panel px-3 py-2 text-xs uppercase tracking-[0.12em] transition-colors hover:border-amber hover:text-amber"><Mail size={16} /><span>Email</span></a></div></motion.div></section> }

export function Marquee() { return <div className="group -mt-8 overflow-hidden border-y border-line py-4 md:-mt-10"><div className="marquee flex w-max gap-8 group-hover:[animation-play-state:paused]">{[...techStack, ...techStack].map((x, i) => <span key={`${x}-${i}`} className="mono text-xs uppercase tracking-widest text-muted">{x}<span className="ml-8 text-amber">✦</span></span>)}</div></div> }

function ProjectCard({ project, onViewDetails }: { project: Project; onViewDetails: (project: Project) => void }) { const isPlaceholder = project.coverImage === '/placeholder.jpg'; return <motion.article variants={reveal} whileInView={{ scale: 1.02, boxShadow: '0 18px 50px rgba(245,166,35,0.16)' }} viewport={{ once: false, amount: 0.55 }} whileHover={{ y: -6 }} transition={{ duration: 0.3, ease }} className={`group flex flex-col justify-between border border-line bg-panel p-6 transition-shadow md:p-8 ${project.featured ? 'md:row-span-2' : ''}`}><div><div className="mb-10 flex items-start justify-between"><span className="mono text-xs text-amber">{project.featured ? 'FEATURED' : 'PROJECT'}</span><div className="flex gap-3 text-muted">{project.githubLink && <a aria-label={`${project.title} GitHub`} href={project.githubLink}><GitHubIcon size={18} /></a>}{project.demoLink && <a aria-label={`${project.title} live demo`} href={project.demoLink}><ExternalLink size={18} /></a>}<button type="button" aria-label={`View details for ${project.title}`} onClick={() => onViewDetails(project)} className="mono text-[10px] uppercase tracking-widest transition-colors hover:text-amber" suppressHydrationWarning>View Details</button></div></div><div className="relative mb-8 aspect-video overflow-hidden border border-line bg-muted/10">{project.coverImage ? <Image src={project.coverImage} alt={isPlaceholder ? '' : `${project.title} screenshot`} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center mono text-[10px] uppercase tracking-widest text-muted">Project screenshot</div>}</div><h3 className="font-display max-w-lg text-2xl font-semibold leading-tight md:text-3xl">{project.title}</h3><p className="mt-5 leading-7 text-muted">{project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="tag">{tag}</span>)}</div></div><div className="mt-12 flex flex-wrap gap-2">{project.highlights.map(item => <span key={item} className="mono border border-line px-2 py-1 text-[10px] text-soft">{item}</span>)}</div></motion.article> }

export function Projects({ onViewDetails }: { onViewDetails: (project: Project) => void }) { return <motion.section id="projects" initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} variants={stagger} className="mx-auto max-w-7xl px-5 py-28 md:px-10"><motion.div variants={reveal}><SectionLabel>Selected work / 02</SectionLabel><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="font-display max-w-2xl text-5xl font-bold tracking-[-0.05em] md:text-7xl">Projects</h2><p className="max-w-xs text-sm leading-6 text-muted">A selection of things I&apos;ve designed, built, and shipped end-to-end.</p></div></motion.div><motion.div variants={stagger} className="grid gap-4 md:grid-cols-2 md:grid-rows-2">{projects.map(project => <ProjectCard key={project.title} project={project} onViewDetails={onViewDetails} />)}</motion.div></motion.section> }

export function Experience() { return <motion.section id="experience" initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} variants={stagger} className="mx-auto max-w-7xl px-5 py-28 md:px-10"><motion.div variants={reveal} className="border-t border-line pt-8"><SectionLabel>Experience / 03</SectionLabel><div className="grid gap-10 md:grid-cols-[1fr_2fr]"><h2 className="font-display text-5xl font-bold tracking-[-0.05em] md:text-7xl">Experience</h2><div className="timeline">{experience.map(item => <article key={item.role} className="timeline-item"><span className="timeline-dot" /><div className="md:flex md:justify-between md:gap-12"><div><h3 className="font-display text-xl font-semibold">{item.role}</h3><p className="mono mt-2 text-xs text-amber">{item.place}</p>{item.bullets && <ul className="mt-5 max-w-2xl space-y-2 text-sm leading-6 text-muted">{item.bullets.map(b => <li key={b}>— {b}</li>)}</ul>}</div><p className="mono mt-4 shrink-0 text-xs text-muted md:mt-1">{item.period}</p></div></article>)}</div></div></motion.div></motion.section> }

function ProjectDialog({ project, onClose }: { project: Project; onClose: () => void }) { const isEmbed = project.videoUrl?.includes('youtube.com') || project.videoUrl?.includes('youtu.be') || project.videoUrl?.includes('loom.com'); return <div role="dialog" aria-modal="true" aria-labelledby="project-dialog-title" className="fixed inset-0 z-[55] flex items-center justify-center bg-ink/80 p-5 backdrop-blur-sm"><motion.div initial={{ opacity: 0, y: 24, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .3, ease }} className="max-h-[85vh] w-full max-w-4xl overflow-y-auto border border-line bg-panel p-6 md:p-10"><div className="mb-8 flex items-start justify-between"><div><SectionLabel>Project details</SectionLabel><h2 id="project-dialog-title" className="font-display max-w-3xl text-4xl font-bold tracking-[-0.05em] md:text-6xl">{project.title}</h2></div><button aria-label="Close project details dialog" onClick={onClose} className="text-muted hover:text-amber"><X /></button></div>{project.videoUrl ? (isEmbed ? <div className="aspect-video overflow-hidden border border-line"><iframe className="h-full w-full" src={project.videoUrl} title={`${project.title} video`} allowFullScreen /></div> : <video className="w-full border border-line" controls src={project.videoUrl} />) : project.coverImage ? <Image src={project.coverImage} alt={`${project.title} cover`} width={1280} height={720} className="w-full border border-line object-cover" /> : null}{project.gallery?.length ? <div className="mt-4 flex gap-3 overflow-x-auto pb-2">{project.gallery.map(image => <Image key={image} src={image} alt="" width={220} height={132} className="h-32 w-52 shrink-0 border border-line object-cover" />)}</div> : null}{project.readme ? <div className="prose prose-invert mt-8 max-w-none text-muted prose-headings:font-display prose-headings:text-soft prose-a:text-amber prose-strong:text-soft"><ReactMarkdown>{project.readme}</ReactMarkdown></div> : null}<div className="mt-8 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="tag">{tag}</span>)}</div><div className="mt-4 flex flex-wrap gap-2">{project.highlights.map(item => <span key={item} className="mono border border-line px-2 py-1 text-[10px] text-soft">{item}</span>)}</div><div className="mt-10 flex flex-wrap gap-3">{project.githubLink && <a href={project.githubLink} className="magnetic inline-flex items-center gap-2 border border-line px-4 py-2 text-sm text-soft hover:border-amber hover:text-amber">GitHub <Code size={16} /></a>}{project.demoLink && <a href={project.demoLink} className="magnetic inline-flex items-center gap-2 bg-amber px-4 py-2 text-sm font-semibold text-ink">Live Demo <ExternalLink size={16} /></a>}</div></motion.div></div> }

function ExperienceDialog({ onClose }: { onClose: () => void }) { return <div role="dialog" aria-modal="true" aria-labelledby="experience-title" className="fixed inset-0 z-[55] flex items-center justify-center bg-ink/80 p-5 backdrop-blur-sm"><motion.div initial={{ opacity: 0, y: 24, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .3, ease }} className="max-h-[85vh] w-full max-w-4xl overflow-y-auto border border-line bg-panel p-6 md:p-10"><div className="mb-10 flex items-start justify-between"><div><SectionLabel>Experience / 03</SectionLabel><h2 id="experience-title" className="font-display text-5xl font-bold tracking-[-0.05em] md:text-7xl">Experience</h2></div><button aria-label="Close experience dialog" onClick={onClose} className="text-muted hover:text-amber"><X /></button></div><div className="timeline">{experience.map(item => <article key={item.role} className="timeline-item"><span className="timeline-dot" /><div className="md:flex md:justify-between md:gap-12"><div><h3 className="font-display text-xl font-semibold">{item.role}</h3><p className="mono mt-2 text-xs text-amber">{item.place}</p>{item.bullets && <ul className="mt-5 max-w-2xl space-y-2 text-sm leading-6 text-muted">{item.bullets.map(b => <li key={b}>— {b}</li>)}</ul>}</div><p className="mono mt-4 shrink-0 text-xs text-muted md:mt-1">{item.period}</p></div></article>)}</div></motion.div></div> }

export function Skills() { return <motion.section id="skills" initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} variants={stagger} className="mx-auto max-w-7xl px-5 py-28 md:px-10"><motion.div variants={reveal} className="grid gap-10 md:grid-cols-[1fr_2fr]"><div><SectionLabel>Toolkit / 04</SectionLabel><h2 className="font-display text-5xl font-bold tracking-[-0.05em] md:text-7xl">Skills</h2></div><div className="space-y-8">{skillGroups.map(group => <motion.div variants={reveal} key={group.label} className="border-t border-line pt-4"><p className="mono mb-4 text-xs uppercase tracking-widest text-muted">{group.label}</p><motion.div variants={stagger} className="flex flex-wrap gap-2">{group.items.map(item => <motion.span variants={reveal} className="tag tag-large" key={item}>{item}</motion.span>)}</motion.div></motion.div>)}</div></motion.div></motion.section> }

export function About() { const bullets = [{ key: 'MERN development', text: 'Building practical web applications with the MERN stack.' }, { key: 'Programming', text: 'Using C++ and Python to build a strong programming foundation.' }, { key: 'Problem solving', text: 'Developing solutions through Data Structures and Algorithms.' }, { key: 'Data & cloud', text: 'Working with SQL and AWS fundamentals.' }, { key: 'Always learning', text: 'Continuously strengthening core software engineering skills.' }, { key: 'Education', text: 'K. J. Somaiya College of Engineering — B.Tech Computer Engineering, Final Year (2023–2027)' }]; return <motion.section id="about" initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} variants={stagger} className="mx-auto max-w-7xl px-5 py-28 md:px-10"><motion.div variants={reveal} className="border-t border-line pt-8"><SectionLabel>About / 03</SectionLabel><div className="grid gap-10 md:grid-cols-[1fr_2fr]"><h2 className="font-display text-5xl font-bold tracking-[-0.05em] md:text-7xl">About</h2><motion.ul variants={stagger} className="grid gap-5 text-base leading-7 text-muted md:grid-cols-2">{bullets.map(item => <motion.li variants={reveal} key={item.key}>— <strong className="text-soft">{item.key}:</strong> {item.text}</motion.li>)}</motion.ul></div></motion.div></motion.section> }

export function Contact() { const socials = [{ label: 'GitHub', handle: '@sentiashish', href: 'https://github.com/sentiashish', icon: GitHubIcon }, { label: 'LinkedIn', handle: 'ashish-kumar-sentiashish', href: 'https://linkedin.com/in/ashish-kumar-sentiashish', icon: LinkedInIcon }, { label: 'Email', handle: 'ashish19@somaiya.edu', href: 'mailto:ashish19@somaiya.edu', icon: Mail }, { label: 'Location', handle: 'Mumbai, India', href: '#contact', icon: MapPin }]; return <motion.section id="contact" initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} variants={stagger} className="mx-auto max-w-7xl px-5 py-28 md:px-10"><motion.div variants={reveal} className="border-t border-line pt-8"><SectionLabel>Contact / 05</SectionLabel><h2 className="font-display text-5xl font-bold tracking-[-0.06em] md:text-8xl">Let&apos;s build<br /><span className="text-amber">something.</span></h2><div className="mt-10 grid gap-4 border-y border-line py-5 text-sm text-muted md:grid-cols-3"><a href="mailto:ashish19@somaiya.edu" className="flex items-center gap-3 hover:text-amber"><Mail size={16} className="text-amber" />ashish19@somaiya.edu</a><span className="flex items-center gap-3"><MapPin size={16} className="text-amber" />Mumbai, India</span><span className="flex items-center gap-3"><Code size={16} className="text-amber" />Open to SWE roles</span></div><div className="mt-10 grid gap-12 md:grid-cols-2"><div><p className="text-muted">Currently looking for full-time SWE roles and internships. Open to relevant opportunities and technical conversations.</p><motion.div variants={stagger} className="mt-8 grid grid-cols-2 gap-3">{socials.map(item => { const Icon = item.icon; return <motion.a variants={reveal} key={item.label} href={item.href} className="border border-line bg-panel p-4 transition-colors hover:border-amber"><Icon size={18} className="mb-5 text-amber" /><p className="font-display font-semibold text-soft">{item.label}</p><p className="mono mt-2 break-all text-[10px] text-muted">{item.handle}</p></motion.a> })}</motion.div></div><form className="space-y-4" onSubmit={sendContactEmail}><label className="sr-only" htmlFor="contact-name">Your name</label><input id="contact-name" name="name" autoComplete="name" placeholder="Your name" required suppressHydrationWarning /><label className="sr-only" htmlFor="contact-email">Your email address</label><input id="contact-email" name="email" autoComplete="email" type="email" placeholder="Your email" required suppressHydrationWarning /><label className="sr-only" htmlFor="contact-message">Your message</label><textarea id="contact-message" name="message" placeholder="Tell me about the project" rows={4} required suppressHydrationWarning /><button type="submit" className="magnetic bg-amber px-5 py-3 text-sm font-semibold text-ink" suppressHydrationWarning>Send via email <ArrowUpRight className="ml-2 inline" size={16} /></button></form></div></motion.div></motion.section> }

export function Footer() { return <footer className="mx-auto flex max-w-7xl flex-col gap-4 border-t border-line px-5 py-8 md:flex-row md:items-center md:justify-between md:px-10"><p className="mono text-[10px] uppercase tracking-widest text-muted">Designed &amp; built by Ashish Kumar · {new Date().getFullYear()}</p><div className="flex gap-4 text-muted"><a aria-label="GitHub" href="https://github.com/sentiashish"><GitHubIcon size={16} /></a><a aria-label="LinkedIn" href="https://linkedin.com/in/ashish-kumar-sentiashish"><LinkedInIcon size={16} /></a></div></footer> }

export function Portfolio() { const [selectedProject, setSelectedProject] = useState<Project | null>(null); useEffect(() => { document.body.style.overflow = selectedProject ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [selectedProject]); return <><ScrollProgress /><Navbar /><main><Hero /><Marquee /><Projects onViewDetails={setSelectedProject} /><Experience /><About /><Skills /><Contact /></main><Footer />{selectedProject && <ProjectDialog project={selectedProject} onClose={() => setSelectedProject(null)} />}</> }
